"""Removed dark mode pref

Revision ID: 3166704a1e40
Revises: 1b234c83f449
Create Date: 2024-08-05 15:26:32.411626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3166704a1e40'
down_revision = '1b234c83f449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('theme_preference')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_preference', sa.VARCHAR(length=5), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
